name: Scheduled Update and Deploy

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Fetch latest data
        run: bun run fetch

      - name: Build project
        run: bun run build
      
      - name: Update config for author
        if: github.actor == 'LittleNyima'
        run: |
          echo 'username: LittleNyima' > config.yaml
          echo 'title: 境界なきキネマ録' >> config.yaml
          echo 'slogan: カオスから芸術まで、物語の深淵を覗き込む。' >> config.yaml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_SSH_SECRET }}
          publish_dir: dist
          publish_branch: deploy
